# Generated by Django 5.0.1 on 2024-01-30 14:06

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='full_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='short_description',
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
