# Generated by Django 5.0.1 on 2024-01-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_category_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Categories/Images/%Y/%m/%d/'),
        ),
    ]
