# Generated by Django 5.0.1 on 2024-01-29 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.category'),
        ),
    ]
