# Generated by Django 5.0.1 on 2024-01-29 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_category_subcategory_alter_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='subCategory',
            new_name='parent',
        ),
    ]
