# Generated by Django 5.0.1 on 2024-02-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('CU', 'Куратор'), ('JC', 'Младший куратор'), ('SEM', 'Старший ивент-мастер'), ('GM', 'Гейм Мастер'), ('EW', 'Ивент-Варден'), ('EM', 'Ивент-Мастер'), ('JEM', 'Младший ивент-мастер'), ('SM', 'Старший модератор'), ('MO', 'Модератор'), ('JM', 'Младший модератор'), ('JU', 'Судья'), ('SEK', 'Верховный жнец'), ('SE', 'Жнец'), ('CM', 'Комьюнити менеджер'), ('SR', 'Старший спрайтер'), ('CM', 'Старший мапер'), ('WE', 'Редактор вики'), ('LC', 'Куратор лора'), ('SA', 'Старший художник'), ('SMM', 'SMM Менеджер'), ('WK', 'Куратор вики'), ('LE', 'Редактор лора'), ('MAP', 'Маппер'), ('SP', 'Спрайтер'), ('YO', 'Ютубер'), ('AR', 'Художник'), ('SD', 'Главный разработчик'), ('SE', 'Главный инженер'), ('DEV', 'Разработчик'), ('JDE', 'Младший разработчик'), ('WAT', 'Смотрящий'), ('TL', 'Переводчик'), ('SK', 'Рыцарь Смока')], default='AR', max_length=40, verbose_name='Type User'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email adress'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('AD', 'Администратор'), ('MA', 'Менеджер')], default='MA', max_length=40, verbose_name='Type User'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=49, null=True, unique=True, verbose_name='User Name'),
        ),
    ]
