# Generated by Django 5.0.1 on 2024-01-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='baners/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Банер',
                'verbose_name_plural': 'Банеры',
            },
        ),
    ]
